pages/urls.py
# coding: UTF-8
from django.urls import path

from pages import views, cbv

app_name = 'pages'
urlpatterns = [
    path('page-list/', views.page_list, name="page_list"),
    path('page-verifications-<int:page_id>/', views.page_verifications, name="page_verifications"),
    path('new-page/', views.new_page, name="new_page"),
    path('delete-page-<int:pk>/', cbv.PageDeleteView.as_view(), name="delete_page"),
]

url_monitor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include('users.urls', namespace='users')),
    path(r'pages/', include('pages.urls', namespace='pages')),
    path(r'verifications/', include('verifications.urls', namespace='verifications')),
    path(r'verification_results/', include('verification_results.urls', namespace='verification_results')),

]

verification_results/urls.py
# coding: UTF-8
from django.urls import path

from verification_results import views

app_name = 'verification_results'

urlpatterns = [
    path('verification-results-<int:page_id>/',
         views.verification_results_by_page,
         name="verification_results_by_page"
         ),

]

verifications/urls.py
# coding: UTF-8
from django.urls import path

from verifications import views

app_name = 'verifications'

urlpatterns = [
    path('new-verification/', views.new_verification, name="new_verification"),

]

verifications/models.py
from django.db import models

# Create your models here.
from pages.models import Page
from users.models import BaseModel
from verification_types.models import VerificationType


class Verification(BaseModel):
    page = models.ForeignKey(
        Page,
        on_delete=models.CASCADE,
        verbose_name="Page à vérifier",
        db_index=True,
        null=False,
        blank=False,
    )

    verification_type = models.ForeignKey(
        VerificationType,
        on_delete=models.CASCADE,
        verbose_name="Type de vérification",
        db_index=True,
        null=False,
        blank=False,
    )

    verification_option = models.CharField(
        verbose_name="Option de vérification",
        max_length=255,
        blank=True,
        null=True,
    )

    description = models.TextField(
        verbose_name="Description",
        default=None,
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.page.title + " " + str(self.verification_type)

    class Meta:
        verbose_name = "Vérification"
        verbose_name_plural = "Vérifications"
        ordering = ("page", "verification_type")

pages/templates/pages/base.html
{% extends "base.html" %}

{% block title %}Pages{% endblock title %}

pages/templates/pages/page_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title_html %}
    Liste des pages
{% endblock %}
{% block content %}
    <a class="btn btn-primary btn-block" href="{% url 'pages:new_page' %}" role="button">Nouvelle page</a>

    <h2>Vos pages</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Page</th>
            <th scope="col">url</th>
            <th scope="col">action</th>

        </tr>
        </thead>
        <tbody>
        {% for page in pages %}
            <tr >
                <th scope="row">{{ page }}</th>
                <td >{{ page.url }}</td>
                <td>
                    <a href="{% url 'pages:page_verifications' page.id %}"> 👁 </a>
                    <a href="{% url 'pages:delete_page' page.id %}"> 🗑 </a>
                    <a href="{% url 'verification_results:verification_results_by_page' page.id %}"> ⛅ </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

pages/templates/pages/page_verifications.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title_html %}
    Liste des vérifications
{% endblock %}
{% block content %}
    <a class="btn btn-primary btn-block" href="{% url 'verifications:new_verification' %}" role="button">Nouvelle vérification</a>

    <h2>Liste des vérification pour : {{ page }}</h2>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Type</th>
                <th scope="col">Option</th>
                <th scope="col">Description</th>

            </tr>
        </thead>
        <tbody>
        {% for verification in page.verification_set.all %}
            <tr>
                <td >{{ verification.verification_type }}</td>
                <td >{{ verification.verification_option }}</td>
                <td >{{ verification.description }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}