pages/urls.py
# coding: UTF-8
from django.urls import path

from pages import views, cbv

app_name = 'pages'
urlpatterns = [
    path('page-list/', views.page_list, name="page_list"),
    path('page-verifications-<int:page_id>/', views.page_verifications, name="page_verifications"),
    path('new-page/', views.new_page, name="new_page"),
    path('delete-page-<int:pk>/', cbv.PageDeleteView.as_view(), name="delete_page"),
]

url_monitor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include('users.urls', namespace='users')),
    path(r'pages/', include('pages.urls', namespace='pages')),
    path(r'verifications/', include('verifications.urls', namespace='verifications')),
    path(r'verification_results/', include('verification_results.urls', namespace='verification_results')),

]

users/urls.py
# coding: UTF-8
from django.urls import path

from users import views

app_name = 'users'
urlpatterns = [
    path(r'hello/', views.hello, name="hello"),
    path('register/', views.register, name="register"),
    path('logout/', views.logout_view, name="logout"),
    path('login/', views.login_view, name="login"),
    path('myaccount/', views.myaccount, name="myaccount"),
    path('account-settings/', views.account_settings, name="account_settings"),
]

url_monitor/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Url Monitor{% endblock title %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    {% load static %}
    <script src="{% static 'js/base.js' %}"></script>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">

    {% block head_end %}{% endblock head_end %}
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">URL Monitor</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin Django</a>
            </li>
        </ul>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'pages:page_list' %}">Pages</a>
            </li>
        </ul>
        {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:logout' %}">Déconnexion</a>
                </li>
            </ul>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:myaccount' %}">{{ user }}</a>
                </li>
            </ul>
        {% else %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:login' %}">Connexion</a>
                </li>
            </ul>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:register' %}">Inscription</a>
                </li>
            </ul>
        {% endif %}


    </div>
</nav>

{% block body_header %}{% endblock body_header %}
<main role="main" class="container" style="padding-top:60px;">

    <div class="starter-template">
        {% block content %}{% endblock content %}
    </div>

</main>

{% block body_footer %}{% endblock body_footer %}

</body>
</html>